name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write


    steps:
      - uses: actions/checkout@v6

      - name: Create Folder
        run: mkdir website

      ######################
      #
      #
      # GH PROFILE
      #
      #
      # ###################

      # Stats for Github Profile
      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=midnight-purple
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Language Card for the Github Profile
      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=8&theme=midnight-purple&hide=markdown,json5,json,yaml,yml
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      ######################
      #
      #
      # WEBSITE
      #
      #
      # ###################

      # For the Website
      - name: Generate top languages card White
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=6&hide=markdown,json5,json,yaml,yml
          path: profile/website/top-langs-white.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # 20 Stats for Card for the Website
      - name: Generate top languages card 20
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=20&hide=markdown,json5,json,yaml,yml
          path: profile/website/top-langs-20.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Finder White for the Website Projects
      - name: Finder Card White
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=shadowdara&repo=finder
          path: profile/website/finder-white.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # justLook White for the Website Projects
      - name: Finder Card White
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=shadowdara&repo=justLook
          path: profile/website/justLook-white.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Add the Cards to the Repo
      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *.svg
          git commit -m "Update README cards" || exit 0
          git push
